### ISSUE TITLE
Navigate results

### ISSUE THREAD

**Issue by xmatthewx** [mmmavis/docs-analyzer#4]
Your little square shortcuts that appear below an issue button are an interesting solution to navigate and see the number of results. 

Could they be a bit bigger? Could we highlight the one the user clicks? Or highlight all that are currently in view?

I wonder if `next` | `previous` arrows would be usefu to navigate the results, in addition to the dots or instead of the dots.

**Comment by mmmavis** [comment]
@xmatthewx 

> Could they be a bit bigger?

Yes. Just need some UI help on this. Currently the sidebar is set to `position: fixed`. Increasing the size of the dots will push everything down and therefore content extends beyond page height will be chopped off / not visible.

>  Could we highlight the one the user clicks? Or highlight all that are currently in view?

Yea I thought about it before... just didn't have time to work on it. Not sure if it'll be laggy to navigate around the matches since a series of calculation will need to happen to make sure right matches are highlighted as users scroll the page. I'll give a try and see how it feels.

> I wonder if next | previous arrows would be usefu to navigate the results, in addition to the dots or instead of the dots. 

Yea I thought about this too. But again, would need some UI suggestion on it as well 😄

**Comment by mmmavis** [comment]
Fixed in https://github.com/mmmavis/docs-analyzer/pull/9 🎉
